### ISSUE TITLE
Couldn't make it work

### ISSUE THREAD

**Issue by drisschelouati** [BPCP/Alfresco-wkhtml2pdf#1]
Hi BPCP,

iam following the thread i started here :https://github.com/deas/contentreich-eml/issues/3#issuecomment-188573629. Well i will give a try adding a rule to see if eml to pdf transformation works correctly and make all the necessary tests. I also wanted to say that i have also tried wkhtml2pdf without success. Here is what i did:

1- download your repo AMP and build it with Maven using `mvn package`.

2- i downloaded wkhtml2pdf from the link and installed it on my windows 10 local machine (in C:\programs and then copied the installation directory to my Alfresco 5.0d installation directory)

3- I installed the AMP, and added the path to `wkhtml2pdf.exe` in `alfresco-global.properties` (i tried both paths : the one in `C:\programs\` and the one in `C:\Alfresco50d\` [neither did work]).

4- then i restarted alfresco, logged in and dragged an eml file from my thunderbird client.

Same thing : "preview could not be loaded from the server" (i dont know the exact error in english since iam working with french translation in Alfresco). So maybe iam doing something wrong, or maybe i should test it on a linux server (i dont know if Libre Office behaves well in windows environments). A the moment i dont have any clue, but i would really like to make this work, and to understand more clearly the transformation services in Alfresco.

Sorry if i was long !! thanks for the awesome work

**Comment by BPCP** [comment]
Check to see if the HTML to PDF works first by uploading an HTML file. If it doesn't I would check the path settings. The global settings file in my source has the path for a Windows setup where I had copied the executables into alfresco. I see I had to use double slashes, I don't member why I needed to do that but I know I did. wkhtmltopdf.exe=C:\\Alfresco\\wkhtmltopdf\\bin\\wkhtmltopdf.exe

I haven't compiled it from source in awhile but I do have an amp file release that should work.

**Comment by drisschelouati** [comment]
ok, i'd like to get the link for your AMP release to test it. I will try your instructions tonight since my dev machine is @ home. So you had to use doubles slahes in your Path ? like how? C:\\ (should i use slahes or anti slashes [anti slashes are for Windows right?])  there are no double slashes in  your example: wkhtmltopdf.exe=C:\Alfresco\wkhtmltopdf\bin\wkhtmltopdf.exe

**Comment by BPCP** [comment]
I didn't even notice that the double slashes didn't copy and paste
correctly.

 the link to releases is
https://github.com/BPCP/Alfresco-wkhtml2pdf/releases

wkhtmltopdf.exe=C:\\Alfresco\\wkhtmltopdf\\bin\\wkhtmltopdf.exe

**Comment by drisschelouati** [comment]
Ok, i think i fixed the path with double slashes (and it only works if wkhtml2pdf installation directory is copied in Alfresco installation root) : C:\\Alfresco\\wkhtml2pdf\\bin\\wkhtml2pdf.exe.

Pdf preview for html docs now works great but still no preview for eml files. Should i add your pipeline to global properties?) :  content.transformer.complex.eml.pdf.pipeline=RFC822|html|OpenOffice.Html2Pdf

thanks

**Comment by BPCP** [comment]
I would comment out the OpenOffice complex transformer that you have in
your global properties so that it doesn't override the settings in my
module.

Alfresco-wkhtml2pdf <https://github.com/BPCP/Alfresco-wkhtml2pdf>/src
<https://github.com/BPCP/Alfresco-wkhtml2pdf/tree/master/src>/main
<https://github.com/BPCP/Alfresco-wkhtml2pdf/tree/master/src/main>/amp
<https://github.com/BPCP/Alfresco-wkhtml2pdf/tree/master/src/main/amp>/
config
<https://github.com/BPCP/Alfresco-wkhtml2pdf/tree/master/src/main/amp/config>
/alfresco
<https://github.com/BPCP/Alfresco-wkhtml2pdf/tree/master/src/main/amp/config/alfresco>
/module
<https://github.com/BPCP/Alfresco-wkhtml2pdf/tree/master/src/main/amp/config/alfresco/module>
/wkhtml2pdf
<https://github.com/BPCP/Alfresco-wkhtml2pdf/tree/master/src/main/amp/config/alfresco/module/wkhtml2pdf>
/*alfresco-global.properties*

You don't want it to use open office at all. The eml to HTML is handled by
the content Reich module and my module converts the HTML to PDF.

My plan was to rewrite the eml to HTML so that it would insert header
information into the PDF ala printing out of Outlook. But there always more
projects than time or ambition.

**Comment by drisschelouati** [comment]
Ok, i will try this tonight. So if i understood what you said : 

1- i should comment out `content.transformer.complex.eml.pdf.pipeline=RFC822|html|OpenOffice.Html2Pdf` in my `alfresco-global.properties` file to deadctivate it, since we dont want to use OpenOffice for this transformation.

2- Then set up the ContentReich module and then it should work? since the Html to PDF transformation now works.

**Comment by BPCP** [comment]
That should do it. Setting up those complex transformers is a real pain but I think that's all it should take.

**Comment by BPCP** [comment]
N second thought, you would be better off copying those transformer settings from my source code into your alfresco-global.properties file. That way you are sure they won't be over written from another module.

**Comment by drisschelouati** [comment]
All right, i get your point. Iam setting up everything tonight for test and i get back to tell you the results. So if i add contentreich preview, its just about mail metadata formatting for the end user.

**Comment by drisschelouati** [comment]
All right, BPCP you are awesome, it works well. However i still got special characters display issues since i use french. However thank you, your work is really good!
